# Generated by Django 6.0.7 on 2026-07-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('lugar_origen', models.CharField(max_length=200)),
                ('historia', models.TextField()),
                ('personajes', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('usada', 'Usada en teatro'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
