# Generated by Django 6.0.7 on 2026-07-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='titulo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='historia',
            name='tradicion',
            field=models.TextField(default=''),
        ),
    ]
